name: deploy
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to develop
        uses: appleboy/ssh-action@master
        env:
          # 服务器上项目路径
          DEV_PROJECT_SERVER_LINUX_PATH: ${{ secrets.DEV_PROJECT_SERVER_LINUX_PATH }}
          LISTEN_IP: 127.0.0.1
          EXPOSE_PORT: '3003'
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_PORT: '27017'
          DATABASE_HOST_NAME: ${{ secrets.DATABASE_HOST_NAME }}
          DATABASE_USER_NAME: ${{ secrets.DATABASE_USER_NAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          ACCOUNT_NEED_LOGIN: 'false'
          TIMEOUT_MS: '100000'
          MAX_REQUEST_PER_HOUR: '20'
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          host: ${{ secrets.HOST_20M }}
          username: ${{ secrets.USERNAME_20M }}
          # key: ${{ secrets.DEPLOY_SECRET }}
          password: ${{ secrets.PASSWORD_20M }}
          # script: cd [path] && git pull && sudo supervisorctl restart param
          envs: DEV_PROJECT_SERVER_LINUX_PATH,LISTEN_IP,EXPOSE_PORT,JWT_SECRET_KEY,DATABASE_NAME,DATABASE_PORT,DATABASE_HOST_NAME,DATABASE_USER_NAME,DATABASE_PASSWORD,ACCOUNT_NEED_LOGIN,TIMEOUT_MS,MAX_REQUEST_PER_HOUR,OPENAI_API_KEY
          script: |
            cd $DEV_PROJECT_SERVER_LINUX_PATH
            git checkout develop
            git pull
            docker build -t chatgpt-web-dev .
            docker stop chatgpt-web-dev
            docker rm -f chatgpt-web-dev
            docker run --name chatgpt-web-dev -d \
              -p $LISTEN_IP:$EXPOSE_PORT:3002 \
              -e JWT_SECRET_KEY=$JWT_SECRET_KEY \
              -e DATABASE_NAME=$DATABASE_NAME \
              -e DATABASE_PORT=$DATABASE_PORT \
              -e DATABASE_HOST_NAME=$DATABASE_HOST_NAME \
              -e DATABASE_USER_NAME=$DATABASE_USER_NAME \
              -e DATABASE_PASSWORD=$DATABASE_PASSWORD \
              -e ACCOUNT_NEED_LOGIN=$ACCOUNT_NEED_LOGIN \
              -e TIMEOUT_MS=$TIMEOUT_MS \
              -e MAX_REQUEST_PER_HOUR=$MAX_REQUEST_PER_HOUR \
              -e OPENAI_API_KEY=$OPENAI_API_KEY \
              chatgpt-web-dev
